configfile: "config/config.yaml"
envvars:
    "GITHUB_TOKEN"

sys.path.insert(0, config['main_wf_dir'] + "/config/")
import config_parser

# Load the configuration
config = config_parser.sub_wf_config_parser(
   main_cfg_fn = config['global_config_path'], 
   sub_wf_name = "lr_bulk")

include: "rules/minimap2.smk"
include: "rules/internal_priming.smk"
include: config['main_wf_dir'] + "/modules/qc.smk"
include: "rules/quantification.smk"
include: config['main_wf_dir'] + "/modules/utilities.smk"

results_dir = config["output_path"]
# make sure the results_dir exists
shell("mkdir -p {results_dir}")

# Email the workflow status
EMAIL = config["email"]



# Main rule
rule all:
   input:
      results_dir + "/.flag/run_all_mapping.done",
      results_dir + "/.flag/run_salmon.done"
   output:
      touch(os.path.join(results_dir, ".flag/all.done"))
   onsuccess:
      shell("mail -s 'DONE: lr_bulk Snakemake run' {EMAIL} < {log}")
   onerror:
      shell("mail -s 'ERROR: lr_bulk Snakemake run' {EMAIL} < {log}")