executor: "slurm"
jobs: 5000
use-conda: true
use-singularity: true
rerun-incomplete: true
singularity-args: "-B /vast/projects/LongBench,/home/users/allstaff/you.yu/LongBench,/vast/scratch/users/you.yu/LongBench,/stornext --env LC_ALL=C.UTF-8,LANG=C.UTF-8"
default-resources:
    mem_mb: 8000
    runtime: 2880
conda-prefix: "/vast/projects/LongBench/analysis/workflow/conda/envs"
singularity-prefix: "/vast/projects/LongBench/analysis/workflow/singularity"
keep-going: false
shadow-prefix: "/vast/scratch/users/you.yu/LongBench/.shadow"
benchmark-extended: true
conda-frontend: conda
rerun-triggers: [ "input", "mtime", "params"] # disable "software-env" "code",