executor: "slurm"
jobs: 500
use-conda: true
use-singularity: true
rerun-incomplete: true
default-resources:
    mem_mb: 8000
    runtime: 2880
conda-prefix: "/vast/projects/LongBench/analysis/workflow/conda/envs"
singularity-prefix: "/vast/projects/LongBench/analysis/workflow/singularity"
keep-going: true
benchmark-extended: true