---
title: "`r params$report_title`"
author: "Yupei"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_float: yes
    number_sections: yes
    toc_depth: 4
  pdf_document:
    toc: yes
    toc_depth: '4'
params:
  report_title: "Untitled"
  random_seed: 2024
  cache_dir: NULL
  preprocessing_script: NULL
  demuxlet_out: NULL
  out_rds: NULL
  in_10x: NULL
---

```{r setup, include=FALSE}
options(future.globals.maxSize = 5 * 1024 * 1024 * 1024)
knitr::opts_chunk$set(echo = T)
knitr::opts_chunk$set(cache = TRUE, cache.path = params$cache_dir)
library(dplyr)
library(tidyverse)
library(Seurat)
library(patchwork)
library(Matrix)
library(ggplot2)
library(gridExtra)
library(stringr)
library(grid)
library(knitr)
library(DT)
library(glue)
library(kableExtra)
```

```{r, set up}
args <- as.list(params)


# set up default args for testing (when not params are provided)
if (is.null(args$in_10x)) {
  args$in_10x <- "/home/users/allstaff/you.yu/LongBench/analysis/illumina_sc_sn/result/cellranger/ill_sc/outs/filtered_feature_bc_matrix"
  args$preprocessing_script <- "sc_processing.R"
  args$demuxlet_out <- "/home/users/allstaff/you.yu/LongBench/analysis/illumina_sc_sn/result/demuxlet/ill_sc.demuxlet.best"
}
```


```{r}
source(args$preprocessing_script)
# make sure the output directory exists
dir.create(dirname(args$out_rds), showWarnings = F, recursive = T)
```


# sing-cell QC and clustring
```{r input file, echo=T, cache=TRUE, warning=F, eval=T}
# input file
so <- load_longbench_result(args$in_10x)
```

## Basic QC

```{r}
# Step 1: Remove Doublet
so <- so %>% remove.doublet %>%  remove_outliers 
so <- so %>% get_clusters(ndim=30,res=0.5,seed = 2024)
## Check the ndim preserve most of the variance:
ElbowPlot(so, ndims = 30, reduction = "pca.Gene_quant")
```

```{r, fig.height=20, fig.width=20}
p <- DimPlot(
  so,
  group.by='seurat_clusters_Gene_quant_res0.5',
  reduction = "umap.Gene_quant",
  combine = FALSE, label.size = 5,
  label = TRUE)
p <-c(p, FeaturePlot(so, features = c("nFeature_Gene_quant", "nCount_Gene_quant", "percent.mt") , combine = F))
do.call(grid.arrange, p)
```

# Part 2: Cell line annotation:
Get demuxlet result
```{r}
# read the demuxlet output:
demuxlet_out <- read.csv(args$demuxlet_out, header = T, sep = '\t') %>% dplyr::select(BARCODE, BEST, SNG.1ST)

demuxlet_out <- demuxlet_out %>% mutate(
  demuxlet.LABEL = case_when(
    substr(BEST, 1, 3) == "SNG" ~ factor(substr(BEST, 5, nchar(BEST))),
    TRUE ~ NA
  ),
  SNG.1ST = factor(SNG.1ST),
  demuxlet.class = substr(BEST, 1, 3)
) %>% dplyr::rename(demuxlet.SNG.1ST = SNG.1ST)


knitr::kable(demuxlet_out, row.names = F) %>% kable_styling(bootstrap_options = "striped",font_size = 10) %>% scroll_box(height = "400px")
```


Merge it to the metadaata of seurat object
```{r}
merged_metadata <- merge(x = so@meta.data, y = demuxlet_out, by.x = "row.names", by.y = "BARCODE", all.x = TRUE)
rownames(merged_metadata) <- merged_metadata$Row.names
so@meta.data <- merged_metadata %>% dplyr::select( -Row.names)
rm(merged_metadata)
```

```{r}
# Summary of different categries of demuxlet output
so$demuxlet.class %>% table
```

```{r, fig.height=10, fig.width=10}

p1 <- DimPlot(
  so,
  group.by = 'demuxlet.class',
  combine = F, label.size = 5,
  label = F)
p1[[1]] <- p1[[1]] + ggtitle("Demuxlet class")

p2 <- DimPlot(
  so[,!is.na(so$demuxlet.LABEL) ],
  group.by = 'demuxlet.LABEL',
  combine = F, label.size = 5,
  label = F)
p2[[1]] <- p2[[1]] + ggtitle("Cell line annotation (Cell classified as SNG)")

p3 <- FeaturePlot(so, features = c("nCount_RNA", "percent.mt") , combine = F)

do.call(grid.arrange, c(p1,
                        p2,
                        p3, ncol=2))

rm(p1, p2, p3)
```
Annotated the original clusters:
```{r}
cluster_anno <- so$seurat_clusters %>% levels() %>% set_names() %>% map_chr( function(x) {
  subset_obj <- subset(so, idents = x)
  prop_table <- table(subset_obj$demuxlet.LABEL) %>% prop.table()
  if (max(prop_table) > 0.9) {
    return(prop_table[which.max(prop_table)] %>% names)
  } else {
    return("AMB")
  }
} )

so@meta.data$cell_lines <- cluster_anno[so$seurat_clusters_Gene_quant_res0.5] %>%  gsub("NCI", '', .)

# plot the annotated cell lines
p <- DimPlot(
  so,
  group.by='cell_lines',
  reduction = "umap.Gene_quant",
  combine = FALSE, label.size = 5,
  label = TRUE)
```


```{r}

saveRDS(so, file = args$out_rds)
```
