configfile: "config/config.yaml"
envvars:
    "GITHUB_TOKEN"

# Load the configuration
sys.path.insert(0, config['main_wf_dir'] + "/config/")
import config_parser
config = config_parser.sub_wf_config_parser(
   main_cfg_fn = config['global_config_path'], 
   sub_wf_name = "sr_sc_sn")



include: "rules/cellranger.smk"
include: "rules/demuxlet.smk"
include: "rules/rmarkdown.smk"

rule all:
    input:
        rules.cellranger.output,
        # rules.demuxlet.output,
        # rules.run_all_rmarkdown.input
