output_path: "/vast/projects/LongBench/analysis/illumina_sc_sn/result"

reference:
  # have to exist
  genome: "/vast/projects/LongBench/reference_files/GRCh38/GRCh38.primary_assembly.genome.fa"
  genome_masked: "/vast/projects/LongBench/reference_files/GRCh38/GRCh38.N-masked.genome.fa"
  gtf: "/vast/projects/LongBench/reference_files/GRCh38/gencode.v44.annotation.gtf"
  gtf_gz: "/vast/projects/LongBench/reference_files/GRCh38/gencode.v44.annotation.gtf.gz"
  picard_reference: "/vast/projects/LongBench/reference_files/GRCh38/refFlat.txt"
  transcript: "/vast/projects/LongBench/reference_files/GRCh38/gencode.v44.transcripts.fa"
  cellline_mutations: "/vast/projects/LongBench/reference_files/celllines_mutation/mutations_subsetted_NAsdropped.csv"
  bed_housekeeping_genes: "/vast/projects/LongBench/reference_files/GRCh38/hg38.HouseKeepingGenes.bed"

# This is current not used in the pipeline, as the data has been basecalled
samples_fastq_dir:
  ill_sc: "/vast/projects/LongBench/sequencing_data/illumina_sc"
  ill_sn: "/vast/projects/LongBench/sequencing_data/illumina_sn"


sample_id:
  ill_sc: "M000495_batch1_2_GEX"
  ill_sn: "M000495_batch1_1_GEX"

sample_name:
  - 'ill_sc'
  - 'ill_sn'