global_config_path: "/vast/projects/LongBench/analysis/workflow/config/config.yaml"
main_wf_dir: "/vast/projects/LongBench/analysis/workflow"



# relative path to the main workflow directory
git_script_dir: "script/git_repo"
conda_config:
  root_path: '/home/users/allstaff/you.yu/LongBench/analysis/workflow/conda/config'
  main: "main.yaml"


# sub workflow config
sub_wf_config:
  lr_sc_sn: /vast/projects/LongBench/analysis/workflow/config/config_lr_sc_sn.yaml
  lr_bulk: /vast/projects/LongBench/analysis/workflow/config/config_lr_bulk.yaml
  sr_sc_sn: /vast/projects/LongBench/analysis/workflow/config/config_sc_sc_sn.yaml


# conda
conda_config_path: '/home/users/allstaff/you.yu/LongBench/analysis/workflow/conda/config'

# for all random process
random_seed: 2024

email: "you.yu@wehi.edu.au"