# result
output_path: "/vast/projects/LongBench/analysis/lr_sc_sn/result_subsample"
#output_path: "/vast/projects/LongBench/analysis/lr_sc_sn/result"
scratch_dir: "/vast/scratch/users/you.yu/LongBench/lr_sc_sn"

# reference file
reference:
  genome: "/home/users/allstaff/you.yu/project/ref_files/GRCh38.primary_assembly.genome.fa"
  gtf: "/home/users/allstaff/you.yu/LongBench/reference_files/GRCh38/gencode.v44.annotation.gtf"
  transcript: "/home/users/allstaff/you.yu/LongBench/reference_files/GRCh38/gencode.v44.transcripts.fa"
  cellline_mutations: '/home/users/allstaff/you.yu/LongBench/reference_files/celllines_mutation/mutations_subsetted_NAsdropped.csv'
  picard_reference: '/home/users/allstaff/you.yu/LongBench/reference_files/GRCh38/refFlat.txt'
  bed_housekeeping_genes: '/home/users/allstaff/you.yu/LongBench/reference_files/GRCh38/hg38.HouseKeepingGenes.bed'

# # This is current not used in the pipeline, as the data has been basecalled
# samples_raw_dir: 
#   ont_sn: "/stornext/Projects/promethion/promethion_access/lab_ritchie/20240523_WEHI_RITCHIE_LongBenchSN_full/long_term/"
#   ont_sc: "/stornext/Projects/promethion/promethion_access/lab_ritchie/20240529_WEHI_RITCHIE_LongBenchSC/long_term/"
  
samples_fastq_dir:
  ont_sn: "/home/users/allstaff/you.yu/LongBench/sequencing_data/ONT_sn/sn_ONT.fastq.gz"
  ont_sc: "/home/users/allstaff/you.yu/LongBench/sequencing_data/ONT_sc/ont_sc.fastq.gz"
  ont_sn_clean: "/home/users/allstaff/you.yu/LongBench/sequencing_data/ONT_sn/ont_sn_clean.fastq.gz"
  ont_sc_clean: "/home/users/allstaff/you.yu/LongBench/sequencing_data/ONT_sc/ont_sc_clean.fastq.gz"
  pb_sc: "/home/users/allstaff/you.yu/LongBench/sequencing_data/pb_sc/pb_sc.fastq.gz"
  pb_sn: "/home/users/allstaff/you.yu/LongBench/sequencing_data/pb_sn/pb_sn.fastq.gz"


# FLAMES were configured into multiple steps, each step can be configured separately
flames_config: 
  genome_mapping: /home/users/allstaff/you.yu/LongBench/analysis/workflow/sub_workflows/lr_sc_sn/config/flames_genome_map.json
  gene_quantification: /home/users/allstaff/you.yu/LongBench/analysis/workflow/sub_workflows/lr_sc_sn/config/flames_gene_quant.json
  flames_trans_map_and_quant: /home/users/allstaff/you.yu/LongBench/analysis/workflow/sub_workflows/lr_sc_sn/config/flames_trans_map_and_quant.json



sample_id:
  # - 'ont_sn'
  # - 'ont_sc'
  - 'ont_sn_clean'
  - 'ont_sc_clean'
  - 'pb_sc'
  - 'pb_sn'

# Config for FLAMES/BLAZE
expected_cells:
  ont_sn: 5000
  ont_sc: 5000
  ont_sn_clean: 5000
  ont_sc_clean: 5000
  pb_sc: 5000
  pb_sn: 5000

count_thres: # Count threshold will override expected_cells
  ont_sn: 
  ont_sc: 
  ont_sn_clean:
  ont_sc_clean:
  pb_sc:
  pb_sn:
 
force_cells: # Count threshold will override expected_cells
  ont_sn: 
  ont_sc: 
  ont_sn_clean: 10000
  ont_sc_clean:
  pb_sc:
  pb_sn: 10000

whitelist_10x:
  ont_sn: 
  ont_sc: 
  ont_sn_clean: 
  ont_sc_clean:
  pb_sc:
  pb_sn:


cell_line_list:
  - H146
  - H69
  - H526
  - H211
  - SHP77
  - H1975
  - H2228
  - HCC827